### ISSUE TITLE
SSL certificate not trusted

### ISSUE THREAD

**Issue by coreation** [jacobsteringa/OdooClient#7]
Hi,

Great work on the client! It works like a charm, unless I try to connect from my production server (locally everything seems fine) to an odoo instance:

stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
  error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

If I tweak the client however to not stop when he can't verify the certificate, everything works fine. So I was wondering if you ran into such troubles yourself, if I should make a PR that optionally adds a Zend Client configured with sslverify false?

Edit: either that or allow somehow to pass the path to the system's cert path.

**Comment by jacobsteringa** [comment]
Hi Jan,

Thank you for taking the time to report this issue and I am glad to hear you like the client!

I have not experienced the issue you described, but it seems serious enough so it should be fixed asap.

IMO the most flexible solution would be to allow users to pass a custom `Zend\Http\Client` to the Odoo client. Either via a optional constructor argument or a setter method.

**Comment by coreation** [comment]
Indeed that would be the most eloquent solution, I'll change my fork and do a PR, it that ok?

**Comment by jacobsteringa** [comment]
Thanks for your PR. I merged it into master and will update the version number later today.

**Comment by coreation** [comment]
You're welcome!
